export {default as Header} from "./Header/Header";
export {default as Hero} from "./Hero/Hero";
export {default as SearchBar} from "./SearchBar/SearchBar";
export {default as Featured} from "./Featured/Featured";
export {default as Footer} from "./Footer/Footer";
export {default as BecomeHost} from "./BecomeHost/BecomeHost";
export {default as PopularCities} from "./PopularCities/PopularCities";
export {default as SearchSideBar} from "./SearchSideBar/SearchSideBar";
export {default as SearchItem} from "./SearchItem/SearchItem";
